<?php
/*
* Generated By Orbisius Child Theme Creator - your favorite plugin for Child Theme creation :)
* https://wordpress.org/plugins/orbisius-child-theme-creator/
*
* Unlike style.css, the functions.php of a child theme does not override its counterpart from the parent.
* Instead, it is loaded in addition to the parent’s functions.php. (Specifically, it is loaded right before the parent theme's functions.php).
* Source: https://codex.wordpress.org/Child_Themes#Using_functions.php
*
* Be sure not to define functions, that already exist in the parent theme!
* A common pattern is to prefix function names with the (child) theme name.
* Also if the parent theme supports pluggable functions you can use function_exists( 'put_the_function_name_here' ) checks.
*/

/**
 * Loads parent and child themes' style.css
 */
function orbisius_ct_astra_child_theme_child_theme_enqueue_styles() {
    $parent_style = 'orbisius_ct_astra_child_theme_parent_style';
    $parent_base_dir = 'astra';

    wp_enqueue_style( $parent_style,
        get_template_directory_uri() . '/style.css',
        array(),
        wp_get_theme( $parent_base_dir ) ? wp_get_theme( $parent_base_dir )->get('Version') : ''
    );

    wp_enqueue_style( $parent_style . '_child_style',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style ),
        wp_get_theme()->get('Version')
    );
}

add_action( 'wp_enqueue_scripts', 'orbisius_ct_astra_child_theme_child_theme_enqueue_styles' );

function add_file_types_to_uploads($file_types){
$new_filetypes = array();
$new_filetypes['svg'] = 'image/svg+xml';
$file_types = array_merge($file_types, $new_filetypes );
return $file_types;
}
add_filter('upload_mimes', 'add_file_types_to_uploads');


function case_studies(){
	$category_query_args = array(
		'category_name' => 'case-studies'
	);
	$category_query = new WP_Query($category_query_args );
	
	$all_post = $category_query->posts;
	echo "<pre>";
	print_r($all_post);
	echo "</pre>";
	die;
	foreach($all_post as $key => $values){
		$title = $values->post_title;
		$image = wp_get_attachment_image_src( get_post_thumbnail_id($values->ID), 'single-post-thumbnail');
		$url = get_permalink($values->ID,false);
		$html ='';
		$html .='<div>';
			$html .='<a href="'.$url.'" class="custom-post">
				<div class="post-image"><img src="'.$image[0].'"></div>
				<h3 class="custom-title">'.$title.'</h3>
				<p>'.get_the_tags($values->ID).'</p>
			</a>';
		$html .='</div>';
		echo $html;
	}
	
}

add_shortcode('case-studies', 'case_studies'); 
